config/routes.rb
Rails.application.routes.draw do
  resources :estimates
  resources :requests
  
  root 'static_pages#home'

end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  belongs_to :request
end

app/models/request.rb
class Request < ActiveRecord::Base
    has_many :estimates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  def new
    @estimate=Estimate.new
    @request=Request.find(params[:r_id])
  end
  
  def create
     @request=Request.find(params[:estimate][:r_id])
     @estimate=@request.estimates.build(params.require(:estimate).permit(:name,:contact,:content))
     if @estimate.save
        redirect_to root_path
      else
        render new
    end
  end


  def edit
    
  end
  
  def show
    @estimate=Estimate.find(params[:id])
    @request=@estimate.request
  end

  
  def index
    @requests=Request.all
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request=Request.new
  end
  
  def create
    @request=Request.new(params.require(:request).permit(:name,:contact,:content))
    if @request.save
      
    else
      render 'new'
    end
    redirect_to root_path
  end

  def edit
    
  end
  
  def show
    @request=Request.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estimate_helper.rb
module EstimateHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/estimates/edit.html.erb
<h1>Estimate#edit</h1>
<p>Find me in app/views/estimate/edit.html.erb</p>

app/views/estimates/index.html.erb
<h2>All Requests:</h2><br>
<% if @requests.nil?||@requests.length==0 %>
No request yet!
<% else %>
<% @requests.each do |e|%>
<%= link_to e.name , e%><br>
<b>Estimates:</b><br>
<% estimates=e.estimates %>
<% if estimates.nil?||estimates.length==0 %>
No estimate yet!
<% else %>
<% estimates.each do |d|%>
<%= link_to d.name , d%><br>
<% end%>
<% end%>
<br><br>
<% end%>
<% end%>

app/views/estimates/new.html.erb
<div>
<h2>Request Info:</h2><br>
<b>Name:</b><br>
<%= @request.name %><br>
<b>Contact:</b><br>
<%= @request.contact %><br>
<b>Content:</b><br>
<%= @request.content %><br>
</div>

<h2>Estimate:</h2>
<div>
  <div>
    <%= form_for(@estimate) do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>

      <%= f.label :contact %><br>
      <%= f.text_field :contact %><br>

      <%= f.label :content%><br>
      <%= f.text_field :content %><br>
      <%= f.hidden_field :r_id, :value => @request.id %>
      <%= f.submit "Create my estimate", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/estimates/show.html.erb
<h2>Request Info:</h2><br>
<b>Name:</b><br>
<%= @request.name %><br>
<b>Contact:</b><br>
<%= @request.contact %><br>
<b>Content:</b><br>
<%= @request.content %><br>



<h2>Estimate Info:</h2>
<b>Name:</b><br>
<%= @estimate.name %><br>
<b>Contact:</b><br>
<%= @estimate.contact %><br>
<b>Content:</b><br>
<%= @estimate.content %><br>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   This is the demo for the reqeust tracking system.
  </small>
  <nav>
    <ul>
       <li><%= link_to "Home", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
     <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Management", estimates_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Request Tracking System</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
     <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      </div>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/requests/edit.html.erb
<h1>Request#edit</h1>
<p>Find me in app/views/request/edit.html.erb</p>

app/views/requests/new.html.erb
<h1>A new request</h1>

<div >
  <div>
    <%= form_for(@request) do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>

      <%= f.label :contact %><br>
      <%= f.text_field :contact %><br>

      <%= f.label :content%><br>
      <%= f.text_field :content %><br>

      <%= f.submit "Create myrequest", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<h2>Request Info:</h2><br>
<b>Name:</b><br>
<%= @request.name %><br>
<b>Contact:</b><br>
<%= @request.contact %><br>
<b>Content:</b><br>
<%= @request.content %><br>

<div>
    <%= link_to "make an estimate" , controller:"estimates", action:"new", r_id: @request.id %>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the request tracking system</h1>

  
  <div>
  <%= link_to "Make a request now!", controller: "requests", action: "new" %></div>
  <div>
  <%= link_to "Make an estimate now!", controller: "estimates", action: "index" %></div>
</div>